[Dev-Settings]
check-syntax = true
write-tokens = true
new-parser = false

[Uranium-Compiler]
no-debug-compiler-output = true
no-process-times = false
std-lib-path = "%URANIUM_PATH%"
reformat-cpp = false

[CPP-Compiler]
compiler = "g++"
args = "-std=c++20 -o ./_out/main.exe"
